from .common import db, Field
from pydal.validators import *

db.define_table('company',
                Field('IAN_FULL_NAME'),
                Field('FIN_TYPE'),
                Field('IM_NUMIDENT'),
                Field('IAN_RO_SERIA'),
                Field('IAN_RO_CODE'),
                Field('IAN_RO_DT', ),
                Field('DIC_NAME'),
                Field('F_ADR'),
                Field('IA_PHONE_CODE'),
                Field('IA_PHONE'),
                Field('IA_EMAIL'),
                Field('IND_OBL'),
                Field('K_NAME'),
                Field('IM_IH'))
db.define_table('payout',
                Field('insurance_type'),
                Field('contract_num', type='integer'),
                Field('case_num', type='integer'),
                Field('insurance_case_date', type='date'),
                Field('statement_date', type='date'),
                Field('requirement_date', type='date'),
                Field('insurance_act_date', type='date'),
                Field('insurance_payment_date', type='date'),
                Field('insurance_payment_size', type='double'),
                Field('settlement_costs', type='double'),
                Field('reserve_size', type='double'),
                Field('kvartal', type='integer'),
                Field('year', type='integer'),
                Field('company_id', 'reference company'))
db.define_table('type',
                Field('name'),
                Field('gross_receipts', type='double'),
                Field('from_residents', type='double'),
                Field('rfrom_insurers_individuals', type='double'),
                Field('rfrom_insurers_legal_entities', type='double'),
                Field('rfrom_reinsurers', type='double'),
                Field('from_non_residents', type='double'),
                Field('nfrom_insurers_individuals', type='double'),
                Field('nfrom_insurers_legal_entities', type='double'),
                Field('nfrom_reinsurers', type='double'),
                Field('payments_return_to_insurers', type='double'),
                Field('payments_return_to_residents', type='double'),
                Field('rpayments_return_to_individuals', type='double'),
                Field('rpayments_return_to_legal_entities', type='double'),
                Field('rpayments_return_to_reinsurers', type='double'),
                Field('payments_return_to_non_residents', type='double'),
                Field('npayments_return_to_individuals', type='double'),
                Field('npayments_return_to_legal_entities', type='double'),
                Field('npayments_return_to_reinsurers', type='double'),
                Field('payments_paid_to_reinsurers', type='double'),
                Field('payments_paid_to_reinsurers_non_resident', type='double'),
                Field('payments_paid_to_reinsurers2', type='double'),
                Field('payments_paid_to_reinsurers2_non_resident', type='double'),
                Field('unearned_premiums', type='double'),
                Field('unearned_premiums_reinsurer', type='double'),
                Field('unearned_premiums_reinsurers_non_resident', type='double'),
                Field('technical_reserves', type='double'),
                Field('reported_unpaid_losses', type='double'),
                Field('unreported_losses', type='double'),
                Field('catastrophe_reserve', type='double'),
                Field('loss_reserve_fluctuations', type='double'),
                Field('share_of_reinsurers_unearned_premiums', type='double'),
                Field('share_of_reinsurers_unearned_premiums_non_resident', type='double'),
                Field('insurance_cases_payments', type='double'),
                Field('insurance_payments', type='double'),
                Field('insurance_payments_residents', type='double'),
                Field('rinsurance_payments_individuals', type='double'),
                Field('rinsurance_payments_legal_entities', type='double'),
                Field('rinsurance_payments_reinsurers', type='double'),
                Field('insurance_payments_non_residents', type='double'),
                Field('ninsurance_payments_individuals', type='double'),
                Field('ninsurance_payments_legal_entities', type='double'),
                Field('ninsurance_payments_reinsurers', type='double'),
                Field('payments_offset_by_reinsurers', type='double'),
                Field('payments_offset_by_reinsurers_non_resident', type='double'),
                Field('maximum_insurance_payment', type='double'),
                Field('acquisition_costs'),
                Field('agency_fees', type='double'),
                Field('agency_fees_non_resident', type='double'),
                Field('costs_reinsurance_contracts', type='double'),
                Field('rewards_brokers', type='double'),
                Field('rewards_brokers_non_resident', type='double'),
                Field('commissions_for_reinsurer', type='double'),
                Field('commissions_for_reinsurer_non_resident', type='double'),
                Field('regulation_of_insured_events_in', type='double'),
                Field('legal_costs_in', type='double'),
                Field('expert_work_in', type='double'),
                Field('emergency_commissioners_in', type='double'),
                Field('expert_work_in', type='double'),
                Field('assistance_agencies_in', type='double'),
                Field('assistance_agencies_in_non_resident', type='double'),
                Field('regulation_of_insured_events_previous', type='double'),
                Field('legal_costs_previous', type='double'),
                Field('expert_work_previous', type='double'),
                Field('emergency_commissioners_previous', type='double'),
                Field('expert_work_previous', type='double'),
                Field('assistance_agencies_previous', type='double'),
                Field('assistance_agencies_previous_non_resident', type='double'),
                Field('number_of_insurance_contracts', type='double'),
                Field('number_contracts_individuals', type='double'),
                Field('number_contracts_legal_entities', type='double'),
                Field('minimum_insurance_amount', type='double'),
                Field('number_of_contracts_not_executed', type='double'),
                Field('number_of_contracts_not_executed_individuals', type='double'),
                Field('total_responsibility', type='double'),
                Field('payables', type='double'),
                Field('quarter', type='integer'),
                Field('year', type='integer'),
                Field('company_id', 'reference company'))
db.commit()